---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

cache: yarn

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

jobs:
  fail_fast: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=typescript-beta
    - env: EMBER_TRY_SCENARIO=ember-cli-beta

  include:
    - stage: "Tests"
      name: "Tests"
      script:
        - test $MD_ONLY && echo "Skipped!" || yarn lint:js
        - test $MD_ONLY && echo "Skipped!" || yarn ci:prepare
        - test $MD_ONLY && echo "Skipped!" || yarn ci:test:app
        - test $MD_ONLY && echo "Skipped!" || yarn ci:test:node
    - stage: "Versioned Tests"
      env: EMBER_TRY_SCENARIO=typescript-release
    - env: EMBER_TRY_SCENARIO=typescript-beta
    - env: EMBER_TRY_SCENARIO=ember-cli-release
    - env: EMBER_TRY_SCENARIO=ember-cli-beta

before_install:
  - bash ./is_md_only.sh && MD_ONLY=true && echo "Only .md files have changed!" || test true
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - test $MD_ONLY && echo "Skipped!" || yarn install

script:
  # Typecheck and compile the addon, then nuke the TS source so we're testing the code we would publish
  - test $MD_ONLY && echo "Skipped!" || yarn ci:prepare
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - test $MD_ONLY && echo "Skipped!" || yarn ember try:one $EMBER_TRY_SCENARIO --skip-cleanup

# We build PRs, but don't trigger separate builds for the PR from the branch.
branches:
  only:
    - master
